# Generated by Django 3.1.1 on 2020-09-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='githublink',
            field=models.URLField(blank=True),
        ),
    ]
